# Generated by Django 5.2.7 on 2025-11-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='issued_by',
            new_name='issued_to',
        ),
    ]
